#
# CVS: $Id: Makefile,v 1.1 2000/01/15 01:45:30 edwardc Exp $
#
#################################################################

all: deljunk

deljunk:
	$(CC) -o deljunk deljunk.c -I../../include

clean: /tmp
	-rm -fr *~ *.o *.BAK

# DO NOT DELETE
